# Generated by Django 3.2.8 on 2023-08-25 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_onlineuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnlineUser',
        ),
    ]
