# Generated by Django 3.2.8 on 2023-08-24 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_auto_20230821_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='chat',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='status',
            field=models.CharField(default='sent', max_length=10),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
